name: Build, SLSA Provenance, Sign & Release

on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r services/backend/requirements.txt
      - name: Build backend image
        run: |
          docker build -f services/backend/Dockerfile -t ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }} .
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          docker tag ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }} ghcr.io/${{ github.repository }}/backend:latest
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}/backend:latest
      - name: Generate SBOM (placeholder)
        run: |
          echo "SBOM generation step goes here"
      - name: Release notes
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true